### ISSUE TITLE
Add some CI/CD system for building and testing the generator's code

### ISSUE THREAD

**Issue by im-konge** [skodjob/test-metadata-generator#2]
As every application, the generator should be build and tested with every PR that will be open to its repository.
We should pick some CI/CD system, that will do following steps:

- build the project and everything needed for testing
- test the code
- possibly push new changes to somewhere
- checkstyle

**Comment by Frawless** [comment]
Build and publish pipeline added as part of https://github.com/skodjob/test-metadata-generator/pull/8

**Comment by Frawless** [comment]
I think majority of the tasks mentioned above is already done. Closing this as done.
