### ISSUE TITLE
Create a release process

### ISSUE THREAD

**Issue by im-konge** [skodjob/test-metadata-generator#4]
For the initial release (and all other releases) we should think about the whole release process and implement particular steps into the repository - including CI/CD, Makefiles for changing the versions and handling various commands.

The whole process should be then documented inside a README.

**Comment by kornys** [comment]
Please do not use makefiles 🙂

**Comment by kornys** [comment]
Releasing into sinatype and github is completed

**Comment by kornys** [comment]
closing as completed
